#    _________  _______       ___  ___      ________      ________      ___           ___      ________       _____ ______
#   |\  _____\|\  ___ \     |\  \|\  \    |\   ___ \    |\   __  \    |\  \         |\  \    |\   ____\     |\   _ \  _   \
#   \ \  \__/ \ \   __/|    \ \  \\\  \   \ \  \_|\ \   \ \  \|\  \   \ \  \        \ \  \   \ \  \___|_    \ \  \\\__\ \  \
#    \ \   __\ \ \  \_|/__   \ \  \\\  \   \ \  \ \\ \   \ \   __  \   \ \  \        \ \  \   \ \_____  \    \ \  \\|__| \  \
#     \ \  \_|  \ \  \_|\ \   \ \  \\\  \   \ \  \_\\ \   \ \  \ \  \   \ \  \____    \ \  \   \|____|\  \    \ \  \    \ \  \
#      \ \__\    \ \_______\   \ \_______\   \ \_______\   \ \__\ \__\   \ \_______\   \ \__\    ____\_\  \    \ \__\    \ \__\
#       \|__|     \|_______|    \|_______|    \|_______|    \|__|\|__|    \|_______|    \|__|   |\_________\    \|__|     \|__|
# Adding Complex Dynamic War to Towny. Created by Hafixion and contributed to by zydde.


